// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjNfNeWflRESOODhyr0lBhqzt_W9O4wg',
    appId: '1:867391642288:web:cb40c9b2b1c0e03e34f975',
    messagingSenderId: '867391642288',
    projectId: 'edu-quest-e8663',
    authDomain: 'edu-quest-e8663.firebaseapp.com',
    storageBucket: 'edu-quest-e8663.appspot.com',
    measurementId: 'G-QR08WF6EK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJh6tXku98XQhSbb6BxCV9_XH1A1jFmvI',
    appId: '1:867391642288:android:30603fe6f9490e0f34f975',
    messagingSenderId: '867391642288',
    projectId: 'edu-quest-e8663',
    storageBucket: 'edu-quest-e8663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHTTVZZJW-Xz8FGGw9kHrWnTXbJQreS5c',
    appId: '1:867391642288:ios:4766d5392fb11ca734f975',
    messagingSenderId: '867391642288',
    projectId: 'edu-quest-e8663',
    storageBucket: 'edu-quest-e8663.appspot.com',
    iosBundleId: 'com.example.eduquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHTTVZZJW-Xz8FGGw9kHrWnTXbJQreS5c',
    appId: '1:867391642288:ios:4766d5392fb11ca734f975',
    messagingSenderId: '867391642288',
    projectId: 'edu-quest-e8663',
    storageBucket: 'edu-quest-e8663.appspot.com',
    iosBundleId: 'com.example.eduquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmjNfNeWflRESOODhyr0lBhqzt_W9O4wg',
    appId: '1:867391642288:web:0ff5ba13c7f575fe34f975',
    messagingSenderId: '867391642288',
    projectId: 'edu-quest-e8663',
    authDomain: 'edu-quest-e8663.firebaseapp.com',
    storageBucket: 'edu-quest-e8663.appspot.com',
    measurementId: 'G-YE927432XP',
  );
}
